### ISSUE TITLE
Icons in sidebar overlaps when docked, and the window height is short

### ISSUE THREAD

**Issue by bluecursor** [dueapp/Due-macOS#12]
When Docked, menu overlaps, When undocked, setting option disappears.
I have also seen a caution icon overlap as well...

<img width="488" alt="Screen Shot 2020-07-28 at 11 15 22 PM" src="https://user-images.githubusercontent.com/31462938/88752736-a677fd80-d128-11ea-83d3-a6e01249660c.png">
<img width="521" alt="Screen Shot 2020-07-28 at 11 15 33 PM" src="https://user-images.githubusercontent.com/31462938/88752738-a841c100-d128-11ea-9078-50ce16d8e743.png">

**Comment by junjie** [comment]
Thanks for reporting the issue @bluecursor. @honcheng, do we not have a minimum height for this?

**Comment by honcheng** [comment]
> do we not have a minimum height for this?

Yes we do. In certain scenario, the minimum height was not respected. 
This is not fixed, and will be available in the next update, 20.2

**Comment by junjie** [comment]
Looking at the screenshot, the window seems to go much shorter than mine. Is there a special reason why?

**Comment by honcheng** [comment]
Aside from minimum window height for the app, there was also a preferred minimum height difference with the screen size when docked, so that the docked window won't be too close to the bottom of the screen. I have reduced the height difference requirement, and also make minimum window height a priority over this.
