### ISSUE TITLE
Option to make “Only this occurrence” as default [Feature Request for iOS and macOS]

### ISSUE THREAD

**Issue by vitorgalvao** [dueapp/Due-macOS#141]
When I **delay** a recurring reminder, I *never* pick “All Future Occurrences”. When I want to **change** a recurring reminder, I always go the longer router of changing it deliberately (which doesn’t have a confirmation popup).

The confirmation popup becomes annoying because I need to be very careful every time it shows up. Plus, when I **delay** multiple reminders at once (which is regular) I always have to do it batches of recurring and non-recurring.

I’d like for there be an option to “Default to “Only this occurrence””. With it on (fine it it’s off by default), Due would always pick that option and never show the popup.

**Comment by junjie** [comment]
> Plus, when I delay multiple reminders at once (which is regular) I always have to do it batches of recurring and non-recurring

I believe this is on macOS, via the editor? 

<img width="427" alt="CleanShot 2021-02-08 at 12 56 02@2x" src="https://user-images.githubusercontent.com/524420/107177534-02dba400-6a0d-11eb-8153-652b4816d036.png">

For bulk editing, I believe we don't show the prompt regardless of whether there are recurring reminders involved, and just treat it as "only this occurrence".

For iOS there is actually a shortcut to trigger only-this-occurrence behaviour. If you swipe the editor away (to the left/right), the edit is saved as this-occurrence-only without prompting you.

**Comment by junjie** [comment]
@vitorgalvao Re-reading this issue from #158, I have more context about why this problem is an issue for you.

> Plus, when I delay multiple reminders at once (which is regular) I always have to do it batches of recurring and non-recurring.

Previously I understood it as an issue with bulk editing, but as mentioned in my [previous comment](https://github.com/dueapp/Due-macOS/issues/141#issuecomment-774866302),  when bulk editing reminders, there is never a prompt for this occurrence/all future occurrence, and recurring reminders are always postponed as "this occurrence only", so that should work according to how you'd want it to behave?

I can understand though that if you use the editor to modify the due date of a single recurring reminder, as you may be trying to do in #158, then that becomes irritating.

If that's the issue at hand, then we can look into adding a [suppression button](https://developer.apple.com/documentation/appkit/nsalert/1535196-showssuppressionbutton) to the prompt, and possibly a preference setting to reset that.

On iOS, there's no concept of a suppression button, so that would probably have to be a preference in Settings.

**Comment by vitorgalvao** [comment]
> If that's the issue at hand, then we can look into adding a [suppression button](https://developer.apple.com/documentation/appkit/nsalert/1535196-showssuppressionbutton) to the prompt, and possibly a preference setting to reset that.
> 
> On iOS, there's no concept of a suppression button, so that would probably have to be a preference in Settings.

I’d be fine with that! iOS in particular can be annoying for these, since they have to be done one at a time (or is there a bulk editing method I’ve missed?)

Apologies on the delay to reply.

**Comment by junjie** [comment]
No worries. For iOS, bulk editing is not available yet. However, a horizontal swipe gesture in the editor saves the reminder, and bypasses the prompt entirely:

https://user-images.githubusercontent.com/524420/117625863-1089fc80-b1a9-11eb-958b-ac046a38b7da.mp4

**Comment by junjie** [comment]
@honcheng For suppression button, I think rather than use the default title of "Do not ask again", we should change the title to reflect something like "Always change only this occurrence".

So when suppression is enabled, we're basically saying that edits to due date of repeating reminders should only apply to the current occurrence in future.

<img width="783" alt="CleanShot 2021-05-10 at 16 03 29@2x" src="https://user-images.githubusercontent.com/524420/117626077-4d55f380-b1a9-11eb-9169-4075eb184824.png">

**Comment by honcheng** [comment]
This feature should be out in the next update, 21.4
