### ISSUE TITLE
Option to snooze daily

### ISSUE THREAD

**Issue by vitorgalvao** [dueapp/Due-macOS#158]
There are a few things that I need to do once a month but may take quite a few days to get to. So I’d like to be able to set those reminders to fire daily, but when marked done they should jump to a certain day on the following month.

The most obvious and simplest way to accomplish this seems to be to add an “Every day” auto-snooze option, but I’m open to alternative methods which accomplish the same.

**Comment by junjie** [comment]
Thanks for the suggestion. Auto-snooze is designed to encourage users to complete/postpone tasks as soon as possible, rather than leaving them overdue. This is meant to prevent the list from becoming stale with lots of overdue items—which I've frequently observed in less persistent todo list/task management apps—and also one of the primary strengths of Due. Adding a one-day option would indeed encourage items to be left overdue for longer than I'd like.

I have items in my list like what you've described—clean the coffee machine, clean the AC—things that don't need to be attended to immediately, but once attended to, should be repeated after a certain duration. Since they're not urgent, they're on less frequent auto snooze (30 minutes or 1 hour). This is still frequent enough to annoy me that I'm motivated to get them out of my way by postponing them to a day where I'm more likely to get to the task. And when that day arrives, I either get to it, or I postpone them again.

I imagine if they're on a hypothetical one-day auto snooze, the motivation to either complete the task or reschedule it to a more appropriate time would be greatly reduced, since they're easily ignored amidst the hustle of the day.

**Comment by vitorgalvao** [comment]
> Adding a one-day option would indeed encourage items to be left overdue for longer than I'd like.

I definitely understand your point. And please, if I suggest a feature you’d rather not implement, please do let me know and feel free to close the issue. You have a vision for the product and shouldn’t be implementing every suggestion.

To give a bit more context, some of my monthly tasks are dependent on someone else—they are reminders of “check if this has been done”. Marking them as complete is a signal I don’t need to worry about it anymore for the rest of the month. That means hourly snoozes become annoying for no reason, making my current method be to disable auto-snooze entirely.

Implementing https://github.com/dueapp/Due-macOS/issues/141 would make this a bit better and I’m also open to other ideas for this specific issue.

But like I said, feel free to close if you feel adding this would make Due worse.

**Comment by junjie** [comment]
Thanks for explaining further. I do have tasks like that from time to time—making sure someone has done something—though they're not usually recurring.

I think we can focus on making it less painful to postpone a recurring task for you in #141, which can probably help you keep it on 1-hour auto snooze if it's easy enough to postpone.

I'll close this for now.
