### ISSUE TITLE
Due ignores trailing punctuation marks on URIs.

### ISSUE THREAD

**Issue by vitorgalvao** [dueapp/Due-macOS#167]
**Feel free to close this issue as will. It is informational, not a bug.**

I use Due to schedule messages, by using the `sms:` URI scheme. Example: `sms:+00000000&body=Some%20Encoded%20Text.`. (Small) Trouble is, Due never considers the last period as part of it (note how it’s in black) nor commas and likely others:

<img width="404" src="https://user-images.githubusercontent.com/1699443/117552279-3a74df00-b042-11eb-8ed2-ae8c958438c5.png">

Technically that can be circumvented by percent encoding it as `%2E`, but while that is trivial on macOS, not so much on iOS via Shortcuts (whose percent-encoding action does not encode those characters—which is correct behaviour). Adding multiple punctuation marks also does not work. What does work is adding a `&` at the end. The character won’t show up, but the previous punctuation mark will.

Now, I understand why Due works the way it does (and maybe it’s not even your choice, but the default) but it may trip people up. Like I said, I’ve found my workaround. So I’m making this issue for two reasons:

1. In case the current behaviour is undesirable, I’d rather know than be relying on a workaround you may break in the future.
2. So you’re aware, in case you weren’t and it ever comes up.

**Comment by junjie** [comment]
Thanks for the detailed report @vitorgalvao. You're right that this is the system default behaviour. In this case, the hyperlinking behaviour is built-in to `NSTextView`. You can see the same behaviour in Apple's Notes.app:

![CleanShot 2021-05-10 at 16 37 31@2x](https://user-images.githubusercontent.com/524420/117630686-074f5e80-b1ae-11eb-8c7e-edc33baff2ec.png)

I believe your workaround with ampersand works because they're frequently found in URLs, whereas a trailing period or exclamation mark is usually not (e.g. "Visit apple.com.", "Visit apple.com!"). As a side note for interest, question marks also get linked, probably because they're frequently used as part of an URL too.

I don't think we'll be diving deep into `NSTextView` to change this behaviour, but thanks for highlighting this and suggesting the workaround so that users who encounter this in future can make use of it.
