### ISSUE TITLE
Hiding sidebar should not change window width

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#177]
https://user-images.githubusercontent.com/524420/133021101-7d44cf43-308f-453e-bd99-bb8f844e9b26.mp4

See comparison between macOS Reminders and Due. Showing sidebar can expand the window width if needed, but hiding the sidebar should never change the window width.

**Comment by honcheng** [comment]
There are 2 options. Either keeping the window width constant (like in Reminders), or changing the window width (like in Contacts). 

The current behaviour changes the window width. That keeps the content view on the right at constant width. During animation, since the content view on the right isn't resized, the animation looks smoother.

If we opt for the first option, the transition isn't smooth. When the content view is resized during animation , text flows to a new line or back to the previous line, and the row height changes. It does not look good. 

The second option, which is the current behaviour looks better.
