### ISSUE TITLE
Do not open main window when invoking with URL handler

### ISSUE THREAD

**Issue by vitorgalvao** [dueapp/Due-macOS#183]
This is the sequence of events when invoking Due with [the URL handler](https://www.dueapp.com/developer.html):

1. Call Due.
2. **The main window** appears.
3. At the same time, a filled editing window appears.
4. `Save` on the editing window.
5. Close **the main window**.

The main window does nothing in this sequence—it’s just an a hindrance to get rid of. Thus, it shouldn’t open at all, just the editing window. Or, alternatively, give us the option to not open it.

**Comment by junjie** [comment]
Thanks for the suggestion!

**Comment by honcheng** [comment]
This issue will be addressed in one the future release that is currently being tested. It will behave differently depending on whether the main window is closed or hidden. The difference is behaviour between closed and hidden is dictated by the OS rather than the app.

- If the app's main window is closed, invoking with URL handler will only bring up the editor.
- If the app's main window is hidden (with CMD-H, or hidden behind other windows), invoking with URL handler will bring forward the window together with the editor.
