### ISSUE TITLE
Shortcuts Mac: Running Due action in a workflow causes Shortcuts to stall

### ISSUE THREAD

**Issue by hey-aw** [dueapp/Due-macOS#194]
Using the Shortcuts app for Mac, it is desirable to create a workflow that results in a new item in Due.

Unfortunately, combining this action with other actions causes a shortcut flow to stall when run.

Steps to reproduce:

1. Open Shortcuts
2. Create a new shortcut
3. Drag `Add Due Reminder` from the Action Library into the shortcut
4. Add some text in the Item input, such as "New item"
5. Add a date in the date field, such as "Tuesday"
6. Run the shortcut

Expected
1. Shortcut creates a new item in due with the item name and date and allows the user to edit it
2. The shortcut execution completes and the workflow terminates naturally

Actual
1. Due correctly interprets the inputs and drafts a new item, but user action is required to save it (this should not require user confirmation)
2. User clicks Save
3. The shortcut execution stalls on this step, never returning to the Shortcuts app and never allowing the Shortcut to terminate

Impacts
1. It is impossible to string together multiple Due shortcuts in a workflow
2. Using Due in any custom shortcut causes Shortcuts to stall
3. It is not possible to create a Due reminder in the background

**Comment by hey-aw** [comment]
This issue is not as severe on iOS, as the user gets an alert with the option to return to Shortcuts. However, choosing "Cancel" there has the same effect as above (Shortcuts is stalled on this step of the workflow, even if you return to the Shortcuts manually.)
![IMG_86D4AF98D1B6-1](https://user-images.githubusercontent.com/106216/147782631-03c237fa-d302-46cd-8171-ad76f3c0f6d4.jpeg)

**Comment by honcheng** [comment]
This issue is related to #146, where support for x-callback-url is not added to Due Mac yet. That's why it does not close the loop in your workflow. We have added support for it, and it will likely be released in the next update. 

> Due correctly interprets the inputs and drafts a new item, but user action is required to save it (this should not require user confirmation)

But at this point, user confirmation (whether to save or cancel) is still required before continuing with the workflow. We have decided that user confirmation is still required at this point because of security, we do not want malicious app to launch Due with URL scheme and modify reminders without confirmation from users. 

To support this, we will need to generate a key that you can provide in Shortcuts (or the URL scheme), but can be addressed separately. 

In the mean time, hope the next update will address your biggest concern.

**Comment by hey-aw** [comment]
Thanks for the update. Nice work!
