### ISSUE TITLE
Using an adjusted date as input to a shortcut does not work when language is not set to English

### ISSUE THREAD

**Issue by clindsay3** [dueapp/Due-macOS#228]
I have a shortcut that creates a reminder "check on the laundry" in 45 minutes. However, when I set my device language to Japanese, the shortcut no longer seems to understand the input time for the shortcut, and instead creates it at noon.

I have tried recreating the reminder in the shortucts app after switching my language to Japanese, and it still doesn't work.

I tried setting the date to "Ask Each Time", and in that case the selected time works correctly. So it seems to be an issue with handling the adjusted time.

Here is a link to the shortcut, and a screenshot of the shortcut in English:
https://www.icloud.com/shortcuts/9f1adfc6a44848a6ac690b59dba7ba0e

![IMG_E5BC8B24EFF5-1](https://user-images.githubusercontent.com/227043/212446562-f5df5a67-57c5-42c6-b91b-28cff85225fc.jpeg)

**Comment by junjie** [comment]
Thanks @chrisvasselli for the report. I can confirm this is happening. 

I have also managed to reproduce this bug when attempting to create a reminder in iOS Reminders.app using the adjusted due date when the system language is set to Japanese:

![IMG_1551](https://user-images.githubusercontent.com/524420/213449542-01a95f0c-b5b1-4ab6-9d08-2f847b008671.PNG)

The first one was created in English. The second one in Japanese. I'm guessing Shortcuts is failing to pass the time component to subsequent actions when the device language is set to Japanese. For Due, that defaults to 12 noon. For Reminders.app, there is no time set.

You can verify this with this shortcut: https://www.icloud.com/shortcuts/2f58801bfc4d40b69256f8eb06b7c3ea

When the system is set to Traditional Chinese, the shortcut works both for Due and Reminders.app. Since this seems to be a bug in Shortcuts when the system is in Japanese, I won't be able to fix this.

You may wish to file a bug report with Apple for their Shortcuts app.

However, I can offer a workaround for you by utilising Due's natural date parser. Here is the shortcut that creates a reminder 45 minutes from now: https://www.icloud.com/shortcuts/5d58cb0d52254b04a9a6abee86efb7d7

**Comment by clindsay3** [comment]
@junjie thanks so much for looking into this! I will file a bug report with Apple about this. Appreciate the workaround too, it's working great!

**Comment by clindsay3** [comment]
Submitted feedback to Apple: FB11958172. 👍

**Comment by junjie** [comment]
Thank you @chrisvasselli!
