### ISSUE TITLE
Crash when attempting to parse an unsupported date/time string twice in a row

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#234]
> Thanks for Due, I use it all the time. I just found a bug in Due Mac.
> 
> Steps to reproduce:
> 
> -- Command-N to create a new reminder
> -- Type "test" in the title field
> -- Press Tab to navigate to the "Due date" field.
> -- Type "noon"
> -- Press Enter
> Due shakes to indicate that it doesn't know what "noon" means
> -- Press Enter again.
> Due crashes.
> 
> Due shouldn't crash, but also it should know what "noon" means!

**Comment by honcheng** [comment]
The crash is fixed. 

But he also mentioned that the app does not attempt to auto complete 'noon'.

<img width="526" alt="CleanShot 2023-05-09 at 11 36 17@2x" src="https://user-images.githubusercontent.com/208827/236987643-6039d09f-9527-43e5-b111-ebd9a5b38c7f.png">

<img width="526" alt="CleanShot 2023-05-09 at 11 36 22@2x" src="https://user-images.githubusercontent.com/208827/236987658-a6447ef2-ff6d-4a59-8b35-5793c9b3a8dd.png">

The body field seems to understand 'noon' and 'midnight' since it is underlining the both words. If we want to support autocompleting noon and midnight, it's as easier as this. But we can write that properly instead of hardcoding. Is this something you want? 

<img width="680" alt="CleanShot 2023-05-09 at 11 35 33@2x" src="https://user-images.githubusercontent.com/208827/236987670-9ab2e74e-055b-4674-af07-ad2f3a46d92a.png">
