### ISSUE TITLE
View > Hide Sidebar

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#40]
One of the request is to make Due's window more compact by hiding the sidebar. Advanced users can still use keyboard shortcuts to get to all the options (switch view with Cmd-1,2,3, create new reminder with Cmd-N, sync with Cmd-Shift-R), while other users can still access them through the appropriate menu items.

This would take a new menu option:

View > Hide Sidebar

When hidden, it should reflect:

View > Show Sidebar

**Comment by honcheng** [comment]
![side-bar-animation 2020-08-24 14_30_33](https://user-images.githubusercontent.com/208827/91011194-6f591700-e616-11ea-9d5f-b3b863016a1a.gif)

We're making some significant progress with this issue. 
Hiding the side bar pushes the standard window buttons on top of the search field, so we need to move the search field as well. Also added keyboard shortcut to toggle the side bar. 

Previous implementation uses 2 container views side-by-side. We've switch to splitView because it has built-in support for toggling side bar that we need. Since the changes is quite big, we'll need to some time to test that this does not introduce new bugs.

**Comment by honcheng** [comment]
This feature will be out in 20.5
