### ISSUE TITLE
Due doesn't honor date formatting preferences

### ISSUE THREAD

**Issue by jacobsa** [dueapp/Due-macOS#46]
I live in Australia, but specifically set my international preferences to use YYYY-MM-DD dates:

<img width="780" alt="Screen Shot 2020-08-05 at 20 22 02" src="https://user-images.githubusercontent.com/202895/89401903-608aed00-d759-11ea-8981-6bd39fad2770.png">

However Due ignores this, showing me the silly DD/MM/YYYY format used in Australia:

<img width="525" alt="Screen Shot 2020-08-05 at 20 22 53" src="https://user-images.githubusercontent.com/202895/89401956-73052680-d759-11ea-9ead-d665f5b7a48f.png">

This significantly increases the cognitive overhead of using Due for me.

**Comment by junjie** [comment]
Thanks, will investigate

**Comment by junjie** [comment]
![89633452-74a82900-d8d6-11ea-91e2-e8105493687f](https://user-images.githubusercontent.com/524420/89633692-cd77c180-d8d6-11ea-99b4-5ef503c3c295.png)

I don't think this is something we can control. I looked at native apps by Apple, including Reminders.app and Calendar.app, and the date picker control is fixed in the format for the region.

Short of making our custom date picker, this is not something that can be addressed with the native date picker.

**Comment by jacobsa** [comment]
Thanks, I see the same thing. That's quite user-hostile, but I guess I have to blame it on Apple.

**Comment by vitorgalvao** [comment]
> That's quite user-hostile, but I guess I have to blame it on Apple.

You can send them a bug report on this via the Feedback Assistant app (`/System/Library/CoreServices/Applications/Feedback Assistant.app`).

**Comment by jacobsa** [comment]
Good idea, done: `FB8342306`
