### ISSUE TITLE
Show/hide keyboard shortcut doesn't work correctly when creating a reminder

### ISSUE THREAD

**Issue by jacobsa** [dueapp/Due-macOS#47]
Steps to reproduce:

1. Press keyboard shortcut to show Due.
2. Press Cmd-N to start creating a reminder.
3. Type something into the reminder box.
4. Press shortcut again to hide Due (e.g. to check on something in the browser that you need to know for the reminder).

In the old version of Due this would correctly hide Due, and then pressing the shortcut again would show Due and you could resume typing. But in the new version step (4) causes the main Due window to gain focus (very surprising; it should hide Due), and then pressing it twice more hides and then shows Due again but without keyboard focus in the right place (the new reminder window).

**Comment by junjie** [comment]
Thanks for the report.

@honcheng:

Based on this behaviour, I assume the Show/Hide shortcut is now checking for whether main window is active, rather than whether Due app is active? 

I think we can solve the problem by changing it such that:

1. it hides Due app as long as Due app is active (instead of checking whether main window active)
2. it activates Due app (the app, not the main window), without attempting to make main window active, such that if the last focused text field before hiding is in the editor text field, it'll remain there?

**Comment by honcheng** [comment]
Thanks. We've fixed this behaviour in 20.4, the next update.
