### ISSUE TITLE
Multiple editing popovers can open if double-click on another cell while window is inactive; crashes on the 3rd one

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#56]
1. Edit a reminder (A)
2. Click on desktop to make Due window lose focus
3. Double click on another reminder (B) without first making Due active

Multiple editors are now opened. Repeat step 2-3 to crash the app.

Reproduction: https://safe.dsh.re/download/00ab896e-3eec-4f33-b070-6a61601d529c

**Comment by FatherOfAlways** [comment]
Related to this (wasn't sure if I should open another ticket):

1. Double click a reminder; editor window opens.
2. Double click the same reminder
3. Repeat step 2

This way, Due crashes reliably (at least on my end).

**Comment by honcheng** [comment]
This is fixed in the upcoming 20.4. 

The correct behaviour should be:
1) If there is an editor for an existing reminder that does not have any changes, it will be closed before a new one is opened.
2) If there is an editor for an existing reminder that has changes, it will not open a new editor, but prompt in existing editor if the changes should be discarded.
