### ISSUE TITLE
Resetting date on editing time

### ISSUE THREAD

**Issue by MrMAB** [dueapp/Due-macOS#76]
I have reminders due to start on thursday 3rd sept with a custom repeat schedule. A typical one is repeating monday, weds, thursday

When I tweak the time, the date is unexpectedly changed to the first repeat in that week - not the first one after the existing date.

E.g. If I set the date to 3rd Sept, with repeat of thurs, monday, weds, I expect a repeat on 3rd, 7th, 9th, 10th sept etc. If then go in and change the time by 5 mins, I don't expect the reminder to jump to 31st august

**Comment by MrMAB** [comment]
Additional: I just changed one with a repeat schedule of tues/weds/thurs and it did not show this behaviour.

**Comment by MrMAB** [comment]
SEEMS to be when changing a repeat schedule that includes monday, the date resets

**Comment by MrMAB** [comment]
I retested again - it seems to be when monday is touched at all.

I had an event scheduled for 15:45 repeating M-F from 3rd sept, and changed it to repeating TWTF at 15:55, and it was moved to repeat from 1st sept.

**Comment by honcheng** [comment]
@MrMAB Thanks for reporting this. I can replicate this bug consistently.

To reproduce: 
1) Create a new reminder due on a later day of the same week. For example, today is Wed, and the reminder is due on Saturday. 
2) Set the reminder to repeat on any day between today (Wed) and a day before due date (Fri). 
3) The due date automatically changes to the earliest repeat date between Wed-Fri. For example, if recurrence is set on Thurs and Sat, the due date will change to Thurs.

**Comment by junjie** [comment]
It's not specific to having Monday in the recurrence. However, whether your week starts Monday will have an impact on how the recurrence changes too.

Basically, when we set up a weekly on day-of-week (DOW) recurrence (which can be every week on some DOW, or every N weeks on some DOW), Due will always go for the **first, non-overdue DOW** of your selection in **that week**.

I understand you're looking for Due to start the recurrence **after** the existing due date, rather than having the possibility of having Due move the due date earlier if there is another earlier DOW.

We'd prefer to just capture the first DOW of the week, and we don't think it's problematic enough to introduce additional UI to confirm whether we should capture the first DOW.

Thanks for the feedback!
